Repository AY2223S2-CS2103T-W13-1/tp, pull requests merged in 2023-03, with the labels that each got.

#34 Add appointment command v0.1
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddDoctorCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Booking.java
  src/main/java/seedu/address/model/appointment/HospitalAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentException.java
  src/main/java/seedu/address/model/person/Doctor.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: bug, duplicate, severity.medium

#35 Update delete feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Story, priority.Medium

#42 Update developer guide
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#44 Update developer guide
  docs/DeveloperGuide.md
Labels: documentation

#41 Fix bug: Duplicate NRIC is allowed
  src/main/java/seedu/address/logic/commands/AddDoctorCommand.java
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/PrescribeCommand.java
  src/main/java/seedu/address/logic/parser/AddDoctorCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Doctor.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RoleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.bug, severity.medium

#48 Assertions not enables in build.gradle
  build.gradle
Labels: priority.High

#45 Add appointment command v0.2
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/HospitalAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/person/Doctor.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/java/seedu/address/logic/commands/AddDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: bug, enhancement, priority.Medium

#55 Update User Guide
  docs/UserGuide.md
Labels: documentation

#60 Update Documentation rename AB-3 to MediConnect
  docs/_sass/minima/_base.scss
  docs/index.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation

#64 Enhance gui v0.2
  src/main/java/seedu/address/model/prescription/Prescription.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonViewPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonViewPanel.fxml
Labels: bug, enhancement, priority.High

#65 Update user guide
  docs/UserGuide.md
  docs/images/AddPatient.png
  docs/images/Appointment.png
  docs/images/Bill.png
  docs/images/Display.png
  docs/images/Edit.png
  docs/images/Prescribe.png
  docs/images/Ui.png
  docs/images/helpMessage.png
  src/main/resources/view/MainWindow.fxml
Labels: documentation

#67 Add list commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListDoctorsCommand.java
  src/main/java/seedu/address/logic/commands/ListPatientsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
Labels: documentation, enhancement, type.Story, priority.Medium

#72 Disable person view display when no contacts are available
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/PersonViewPanel.java
  src/main/resources/view/PersonViewPanel.fxml
Labels: bug
