Repository AY2223S2-CS2103T-W13-1/tp, pull requests merged in 2023-04, with the labels that each got.

#122 Bugfix issue89
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.bugfix

#123 Bugfix issue113
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.bugfix

#125 Bugfix issue119
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
Labels: type.bugfix

#120 Fix message displayed when failing to add a Patient
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/model/person/Doctor.java
  src/main/java/seedu/address/model/person/Patient.java
Labels: documentation, priority.Medium, type.bug

#121 Fix message displayed when failing to add a Doctor
  src/main/java/seedu/address/logic/commands/AddDoctorCommand.java
Labels: priority.Medium, type.bug

#126 UserGuide: Update Command Summary prescribeCommand
  docs/UserGuide.md
  src/main/java/seedu/address/model/prescription/Cost.java
Labels: type.bugfix

#124 Update thennant ppp
  docs/team/thennant.md
Labels: documentation

#129 Bugfix issue75
  docs/UserGuide.md
Labels: type.bugfix

#132 Fix issue110
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.bugfix

#137 Fix issue114
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
Labels: type.bugfix

#131 Bugfix issue77
  docs/UserGuide.md
  docs/images/AddDoctor.png
  docs/images/AddPatient.png
  docs/images/Appointment.png
  docs/images/Bill.png
  docs/images/Clear.png
  docs/images/DeleteAppointment.png
  docs/images/Delete_after.png
  docs/images/Delete_before.png
  docs/images/Display.png
  docs/images/Edit.png
  docs/images/Find.png
  docs/images/List.png
  docs/images/ListDoctors.png
  docs/images/ListPatients.png
  docs/images/Prescribe.png
  docs/images/Ui.png
  docs/images/Unprescribe.png
  docs/images/johndoe.png
Labels: documentation

#144 Update developer guidev3
  docs/DeveloperGuide.md
  docs/images/deleteState0.png
  docs/images/deleteState1.png
  docs/images/deleteState2.png
Labels: documentation

#147 Update thennant pppv2
  docs/team/thennant.md
Labels: documentation

#153 Update stefanosav PPP
  docs/AboutUs.md
  docs/team/stefanosav.md
Labels: documentation

#152 Update DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/AddDoctorSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AddDoctorSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/LogicClassDiagram.png
Labels: documentation

#154 Update Ui component diagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: documentation, type.bugfix

#146 Update developer guidev4
  docs/DeveloperGuide.md
Labels: documentation

#159 Update Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AddPatient.png
  docs/images/Appointment.png
  docs/images/Bill.png
  docs/images/Display.png
  docs/images/Edit.png
  docs/images/Find.png
  docs/images/ListDoctors.png
  docs/images/ListPatients.png
  docs/images/ModelClassDiagram.png
  docs/images/Prescribe.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/team/stefanosav.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: documentation

#160 Update developer guidev5
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: documentation

#163 fix formatting of acknowledgments
  docs/DeveloperGuide.md
Labels: documentation

#161 Update code quality
  docs/team/stefanosav.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddDoctorCommand.java
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/parser/AddDoctorCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/BillCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DisplayCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/PrescribeCommandParser.java
  src/main/java/seedu/address/logic/parser/UnprescribeCommandParser.java
  src/main/java/seedu/address/model/person/Doctor.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Role.java
  src/test/java/seedu/address/logic/commands/AddDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
Labels: enhancement

#164 fix image size for step 2 in undo/redo feature in DG
  docs/DeveloperGuide.md
Labels: documentation

#168 Update user guidev4
  docs/UserGuide.md
Labels: documentation

#169 added more pg breaks
  docs/UserGuide.md
  docs/team/thennant.md
Labels: documentation

#170 finalised layout of UG
  docs/UserGuide.md
Labels: documentation

#173 fix DG page breaks
  docs/DeveloperGuide.md
Labels: documentation

#174 fix page break for DG
  docs/DeveloperGuide.md
Labels: documentation

#176 fix page break for DG
  docs/DeveloperGuide.md
Labels: documentation
